@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Felipe Amorim",
  "email": "felipe5@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "felipe1@gmail.com",
  "password": "123456"
}

###

# @name create_exercise
POST {{baseUrl}}/exercises
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Rosca Scott",
  "videoUrl": "http://youtube.com",
  "description": "Exercicio trabalha o peito inferior",
  "groupMuscle": [
    {
      "id": "fde6515e-3727-46f5-b446-451eb926997a",
      "name": "Biceps"
    }
  ]
}

###

# @name edit_exercise
PUT {{baseUrl}}/exercises/2cd3747a-bc4b-4f4a-af6c-46a4013e6d29
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Supino Inclinado",
  "description": "Exercicio trabalha o peito inferior"
}

###

# @name delete_exercise
DELETE  {{baseUrl}}/exercises/2cd3747a-bc4b-4f4a-af6c-46a4013e6d29
Authorization: Bearer {{authToken}}

###

# @name create_training-plan
POST {{baseUrl}}/training-plans
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "studentId": "e42edb74-d88d-44f1-8383-118a97f8f4a0",
  "name": "Plano Trimestral a Vencer",
  "goal": "Emagrecimento",
  "sessionsPerWeek": 4,
  "trainingLevel": "Intermediario",
  "strategy": "FLEXIBLE_SESSIONS",
  "startDate": "2025-02-03T03:00:00.000Z",
  "endDate": "2025-02-03T03:00:00.000Z"
}

###

# @name create_training
POST {{baseUrl}}/trainings
Authorization: Bearer {{authToken}}
Content-Type: application/jsonmy-progress
{
  "trainingPlanId": "2f8bebb8-0817-4448-b672-20fe08c7eb3c",
  "name": "TREINO B",
  "type": "SESSION",
  "groupMuscle": [
    {
      "name": "Triceps",
      "id": "472dcea4-60c4-4557-ba5d-6849c33256a1"
    },
    {
      "name": "Ombro",
      "id": "53bdcc47-91cb-406d-8a84-d7c04d0bdd12"
    }
  ],
  "exercises": [
    {
      "exerciseId": "82901f83-e697-4500-a5d6-5c589891e686",
      "sets": 3,
      "repetitions": 12,
      "restTime": 120
    },
    {
      "exerciseId": "33fd5c93-37bb-4c20-baaf-47ebe830d158",
      "sets": 3,
      "repetitions": 12,
      "restTime": 120
    }
    ,
    {
      "exerciseId": "e1913045-7243-4d43-8152-2ba2d222b493",
      "sets": 3,
      "repetitions": 12,
      "restTime": 120
    }
    ,
    {
      "exerciseId": "c464024a-38de-4116-a01d-aa3c254ecefb",
      "sets": 3,
      "repetitions": 12,
      "restTime": 120
    }
    ,
    {
      "exerciseId": "e0cb4a57-e7b1-423a-afd5-d8cfdfcf9511",
      "sets": 3,
      "repetitions": 12,
      "restTime": 120
    }
    ,
    {
      "exerciseId": "3a6e2a16-30a3-40b2-aa51-51ae8bd5fe7f",
      "sets": 3,
      "repetitions": 12,
      "restTime": 120
    }
    ,
    {
      "exerciseId": "99b19dca-48d6-4b10-a537-62b946f0569b",
      "sets": 3,
      "repetitions": 12,
      "restTime": 120
    },
    {
      "exerciseId": "55976c1e-ad14-4920-b732-7d6b3790e28f",
      "sets": 3,
      "repetitions": 12,
      "restTime": 120
    },
    {
      "exerciseId": "d054c3eb-b1c4-4f50-9d94-8abfff28c017",
      "sets": 3,
      "repetitions": 12,
      "restTime": 120
    }
  ]
}

###

# @name create_training_feedback
POST {{baseUrl}}/trainings/feedback
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "trainingId": "14f43bd7-4e3d-4640-915c-3a6701918136",
  "rate": 2,
  "comment": "Otimo treino, tive um pouco de dificuldade no primeiro exercicio mas depois foi tranquilo2.",
  "exercises": [
    {
      "exerciseId": "47597df6-b360-4197-a828-31526641f35f",
      "weightUsed": 20 
    }
  ]
}

###

# @name reply_training_feedback
POST {{baseUrl}}/trainings/feedback/98d7b8a4-a509-492f-befb-09e24b4f8bc5/reply
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "reply": "Continue firme no progresso!"
}

###

# @name read_training_feedback_reply
PUT {{baseUrl}}/trainings/feedbacks/reply/fb1a4a1c-1d23-41db-a710-a705b1de79e8
Authorization: Bearer {{authToken}}


###

# @name update_student_profile
PUT {{baseUrl}}/profile
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Felipe Douglas"
}

###

# @name create_my_progress
POST {{baseUrl}}/my-progress
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "photo": "userphoto.jpg",
  "comment": "Oque acha do meu fisico?"
}
###

# @name create_my_progress_answer_admin
POST {{baseUrl}}/my-progress/215ef3e4-ce50-4db6-957e-9810e4100c22/answer
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "reply": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
}

###

# @name create_body_composition_pullock
POST {{baseUrl}}/body-composition
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "studentId": "student-1",
  "height": 163,
  "weight": 80,
  "age": 29,
  "gender": "MALE",
  "abdominal": 90,
  "chest": 120,
  "hip": 70,
  "waist": 100,
  "suprailiac": 80,
  "thigh": 60,
  "triceps": 22
}

###

# @name create_anamnesis
POST {{baseUrl}}/anamnesis
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "fullName": "John Doe",
  "age": 29,
  "hadChestPainInLastMonth": false,
  "hasBalanceProblems": true,
  "hasBoneOrJointProblem": false,
  "hasChestPainDuringActivity": true,
  "hasHeartProblem": false,
  "hasOtherHealthIssues": false,
  "takesBloodPressureMedication": true
}



###

# @name fetch_training-plan
GET {{baseUrl}}/training-plans
Authorization: Bearer {{authToken}}

###

# @name fetch_trainings
GET {{baseUrl}}/trainings?trainingPlanId=2f8bebb8-0817-4448-b672-20fe08c7eb3c
Authorization: Bearer {{authToken}}


###

# @name fetch_training_exercises
GET {{baseUrl}}/trainings/exercises?trainingId=6e8380ca-a8eb-4dcc-abba-97b6898215a3
Authorization: Bearer {{authToken}}

###

# @name fetch_training_feedbacks_user
GET {{baseUrl}}/trainings/feedback/user
Authorization: Bearer {{authToken}}
###

# @name fetch_training_feedbacks_admin
GET {{baseUrl}}/trainings/feedback?page=1
Authorization: Bearer {{authToken}}

###

# @name fetch_exercise_executions
GET {{baseUrl}}/exercises/e1913045-7243-4d43-8152-2ba2d222b493/execution?page=1
Authorization: Bearer {{authToken}}

### 
# @name fetch_exercise_executions_by_user
GET {{baseUrl}}/exercises/executions
Authorization: Bearer {{authToken}}


    CreateAnamnesisUseCase,
Authorization: Bearer {{authToken}}

### 
# @name find_recent_exercise_weight
GET {{baseUrl}}/exercises/82901f83-e697-4500-a5d6-5c589891e686/executions
Authorization: Bearer {{authToken}}

### 
# @name get_profile
GET {{baseUrl}}/profile
Authorization: Bearer {{authToken}}

###

# @name  fetch_my_progress_update
GET {{baseUrl}}/my-progress
Authorization: Bearer {{authToken}}

###

# @name  fetch_body_composition
GET {{baseUrl}}/body-composition
Authorization: Bearer {{authToken}}

###

# @name  fetch_anamnesis
GET {{baseUrl}}/anamnesis
Authorization: Bearer {{authToken}}

### @name find_body_composition
GET {{baseUrl}}/body-composition/9abcaa54-238f-44f9-b1a5-1a96ef5b23ac
Authorization: Bearer {{authToken}}

